# Generated by Django 5.2.5 on 2025-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('none', 'No Plan'), ('basic', 'Basic'), ('premium', 'Premium'), ('advanced', 'Advanced')], db_index=True, default='none', max_length=10),
        ),
    ]
