# Generated by Django 5.2.5 on 2025-09-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_device_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
