# Generated by Django 5.2.5 on 2025-10-22 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone must be 7–15 digits, optional leading +.', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
