# Generated by Django 5.2.5 on 2025-10-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id_1',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_id_2',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
