# Generated by Django 5.2.5 on 2025-10-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_coupon_plan_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('none', 'No Plan'), ('basic', 'Basic'), ('premium', 'Premium'), ('advanced', 'Advanced')], db_index=True, max_length=32, unique=True),
        ),
    ]
