# Generated by Django 5.2.5 on 2025-11-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='users.payment'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], db_index=True, default='active', max_length=16),
        ),
    ]
