# Generated by Django 5.2.5 on 2025-11-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subscription_payment_alter_subscription_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
