# Generated by Django 5.2.5 on 2025-09-16 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
            ],
            options={
                'ordering': ['year__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='edu.semester')),
            ],
            options={
                'ordering': ['semester__year__order', 'semester__order', 'order', 'id'],
                'unique_together': {('semester', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='edu.module')),
            ],
            options={
                'ordering': ['module__semester__year__order', 'module__semester__order', 'module__order', 'order', 'id'],
                'unique_together': {('module', 'name')},
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='edu.year'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='edu.subject')),
            ],
            options={
                'ordering': ['subject__module__semester__year__order', 'subject__module__semester__order', 'subject__module__order', 'subject__order', 'order', 'id'],
                'unique_together': {('subject', 'title')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'name')},
        ),
    ]
