# Generated by Django 5.2.5 on 2025-09-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('written', 'Written')], max_length=20)),
                ('source_type', models.CharField(choices=[('qbank', 'Q Bank'), ('exam_review', 'Exam Review'), ('tbl', 'TBL'), ('flipped', 'Flipped'), ('old_exam', 'Old Exam')], max_length=20)),
                ('exam_kind', models.CharField(choices=[('none', 'Not Exam'), ('midterm', 'Midterm'), ('final', 'Final')], default='none', max_length=10)),
                ('exam_year', models.CharField(blank=True, max_length=20, null=True)),
                ('grade', models.CharField(choices=[('na', 'Not Applicable'), ('a', 'Grade A'), ('b', 'Grade B'), ('c', 'Grade C')], default='na', max_length=2)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edu.lesson')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edu.subject')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edu.year')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='edu.question')),
            ],
        ),
    ]
