# Generated by Django 5.2.5 on 2025-09-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_question_questionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Link here if the question belongs to a Module (Exam Review or Old Exam).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edu.module'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, help_text='Model answer text if the question is Written type.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_kind',
            field=models.CharField(choices=[('none', 'Not Exam'), ('midterm', 'Midterm'), ('final', 'Final')], default='none', help_text='Required only if the question belongs to an Exam (Midterm/Final).', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_year',
            field=models.CharField(blank=True, help_text='Specify the year of the exam (e.g., 2021) if the source is Exam Review or Old Exam.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation of the correct answer (optional, shown after solving).', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.CharField(choices=[('na', 'Not Applicable'), ('a', 'Grade A'), ('b', 'Grade B'), ('c', 'Grade C')], default='na', help_text='Required only if the question is from Old Exam, to specify grade (A/B/C).', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Use when the question is linked to a Lesson (QBank or TBL/Flipped).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edu.lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('written', 'Written')], help_text='Type of the question: MCQ (multiple choice) or Written (open text).', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_type',
            field=models.CharField(choices=[('qbank', 'Q Bank'), ('exam_review', 'Exam Review'), ('tbl', 'TBL'), ('flipped', 'Flipped'), ('old_exam', 'Old Exam')], help_text='Source of the question: QBank, Exam Review, TBL, Flipped, Old Exam.', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Use when the question is linked to a Subject (Exam Review, TBL, or Flipped).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edu.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='The main text of the question as shown to the student.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.ForeignKey(blank=True, help_text='Use when the question is linked to a full Year (Exam Review or Old Exam).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edu.year'),
        ),
    ]
