# Generated by Django 5.2.5 on 2025-09-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_question_module_alter_question_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='code',
            field=models.CharField(choices=[('y1', 'Year 1'), ('y2', 'Year 2'), ('y3', 'Year 3'), ('y4', 'Year 4'), ('y5', 'Year 5')], db_index=True, default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
