# Generated by Django 5.2.5 on 2025-09-23 16:49

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_favoritelesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='lesson_pdfs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
