# Generated by Django 5.2.5 on 2025-09-27 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_lesson_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['owner_type', 'owner'], name='edu_flashca_owner_t_23b376_idx'),
        ),
    ]
