# Generated by Django 5.2.5 on 2025-10-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_plannertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='part_type',
            field=models.CharField(choices=[('theoretical', 'Theoretical'), ('practical', 'Practical')], db_index=True, default='theoretical', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='part_type',
            field=models.CharField(choices=[('theoretical', 'Theoretical'), ('practical', 'Practical')], db_index=True, default='theoretical', max_length=20),
        ),
    ]
