# Generated by Django 5.2.5 on 2025-10-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_lesson_part_type_question_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='optional : image with question', null=True, upload_to='question_images/%Y/%m/%d/'),
        ),
    ]
