# Generated by Django 5.2.5 on 2025-10-03 00:01

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='optional : image with question', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='question_images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
