# Generated by Django 5.2.5 on 2025-10-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_flipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_tbl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_type',
            field=models.CharField(choices=[('qbank', 'Q Bank'), ('exam_review', 'Exam Review'), ('old_exam', 'Old Exam')], help_text='Source of the question: QBank, Exam Review, TBL, Flipped, Old Exam.', max_length=20),
        ),
    ]
