# Generated by Django 5.2.5 on 2025-10-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0017_alter_lesson_pdf_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_ready',
            field=models.BooleanField(db_index=True, default=False, help_text='Only ready modules are visible to students.'),
        ),
    ]
