# Generated by Django 5.2.5 on 2025-09-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', models.BinaryField()),
                ('faiss_id', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['file_name', 'chunk_index'], name='rag_ai_chun_file_na_43ae29_idx'), models.Index(fields=['faiss_id'], name='rag_ai_chun_faiss_i_6ec77b_idx')],
                'unique_together': {('file_name', 'chunk_index')},
            },
        ),
    ]
