# Generated by Django 5.2.5 on 2025-09-18 04:57

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='embedding_vec',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
